name: CI

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: yarn

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check format
        run: yarn format:check

      - name: Check spell
        run: yarn spell:check

      - name: Build HTML
        run: yarn build:html