name: Release PDF and Public GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install
        run: yarn install

      - name: Check format
        run: yarn format:check

      - name: Check spell
        run: yarn spell:check

      - name: Build
        run: yarn build:html

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          path: _book
          name: book
          overwrite: true
